variable "zone_id" { default = "Z19XWJP91YHTWW" }
variable "cluster_name" { default = "emea-edp-vault" }
variable "environment" { default = "dev" }
variable "ami_id" { default = "ami-XXXXXX" }
variable "instance_type" { default = "t2.micro" }
variable "ssh_key" { default = "emea-build-2" }
variable "cluster_tag_key" { default = "cluster-servers" }
variable "vpc" { default = "vpc-6000f708" }
variable "subnet_ids" { default = [ "subnet-23e4454a", "subnet-478fa30a", "subnet-115a446a" ] }
variable "avail_zones" { default = [ "eu-west-2a", "eu-west-2b" , "eu-west-2c" ] }
variable "allowed_cidrs" { default = [ "10.0.0.0/8" ] }
variable "api_port" { default = 8200 }
variable "cluster_port" { default = 8201 }
variable "rpc_port" { default = 8300 }
variable "serf_lan_port" { default = 8301 }
variable "serf_wan_port" { default = 8302 }
variable "cli_port" { default = 8400 }
variable "http_port" { default = 8500 }
variable "dns_port" { default = 8600 }
variable "https_port" { default = 8900 }
