- name: enable consul service
  service: name=consul enabled=yes state=started

- name: enable sysv supervisord service
  service: name=vault enabled=yes state=started

- name: Restart the server
  command: /sbin/shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true
